name: Deploy Orlando Server
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_DO_Token: ${{ secrets.DO_Token }}
  TF_VAR_MYSQL_DB: ${{ secrets.MYSQL_DB }}
  TF_VAR_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  TF_VAR_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  TF_VAR_MYSQL_USER: ${{ secrets.MYSQL_USER }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setip-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false
      - name: Create SHH keys from secrets
        run: |
          mkdir keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}"> ./keys/orlando_server
          echo "${{ secrets.SSH_PUBLIC_KEY }}"> ./keys/orlando_server.pub
          chmod 777 ./keys/orlando_server
          chmod 777 ./keys/orlando_server.pub
      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt 

      - name: Terraform validate
        run: terraform validate 

      # - name: Terraform plan
      #   run: terraform plan

      # - name: Terraform apply
      #   run: terraform apply --auto-approve